services:
    oklm_app.article.listener:
        class: OKLM\AppBundle\Listener\ArticleListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    oklm_app.article.manager:
        class: OKLM\AppBundle\Manager\ArticleManager
        arguments:
            - @doctrine.orm.entity_manager
            - OKLM\AppBundle\Entity\Article

    oklm_app.article.form_type:
        class: OKLM\AppBundle\Form\ArticleType
        tags:
            - { name: form.type, alias: oklm_appbundle_article }

#    oklm_app.example:
#        class: OKLM\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
