services:
    oklm_app.article.listener:
        class: OKLM\AppBundle\Listener\ArticleListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

#    oklm_app.example:
#        class: OKLM\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
